name: Build Blender with DLSS PR

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Enable long paths in Git and Windows
        shell: pwsh
        run: |
          git config --system core.longpaths true

      - name: Clone Blender Source and PR
        shell: bash
        run: |
          git clone --depth 1 https://projects.blender.org/blender/blender.git src
          cd src
          git fetch origin refs/pull/153077/head:dlss-pr
          git checkout dlss-pr

      - name: Download SVN Precompiled Libs
        shell: cmd
        run: |
          cd src
          echo y | make.bat update

      - name: Build Blender
        shell: cmd
        run: |
          cd src
          echo y | make.bat release

      - name: Archive Build Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Blender-DLSS-Windows-x64
          path: build_windows_Full_x64_vc17_Release/bin/*
          retention-days: 7
